refactor reloader.bash for better error handling
Bash-it/bash-it pull request #1761
Opened 2021-01-03 05:02 UTC by cornfeedhobo

## Description

Using a recursive function enables the checking of issues in a script,
including any `exit` calls from any children. Verifying this offers protection
for the user against their shell closing if something is broken downstream.

## Motivation and Context

@NoahGorny asked about logging success conditions, and I said I'd rather centralize that. This addresses that, and more.

## How Has This Been Tested?

Locally

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-01-03 16:02 UTC, cornfeedhobo commented
I have an improvement that I want to investigate before merging. Hold off.

2021-01-07 18:05 UTC, NoahGorny requested changes
I really like this change @cornfeedhobo, I have two comments though that needs to be addressed IMO

2021-01-07 18:05 UTC, NoahGorny commented on scripts/reloader.bash
> +				while read -r line; do _log_debug "$line"; done <<< "$output"
this also causes log messages in the plugin to be displayed twice (once regularly and once by this line)
we currently print logs to stdout, so maybe only catch output of stderr to display

2021-01-13 16:26 UTC, NoahGorny commented
ping @cornfeedhobo

2021-01-13 16:31 UTC, cornfeedhobo commented
@NoahGorny I've had some family stuff came up. I'll get back to everything as soon as possible,

2021-01-13 16:32 UTC, NoahGorny commented
> @NoahGorny I've had some family stuff came up. I'll get back to everything as soon as possible,

No worries, no need to feel rushed :smile:
I hope you are doing okay, and have a great day!

2021-01-13 16:33 UTC, cornfeedhobo commented
@NoahGorny sorry. I need more time. I have other priorities at the moment.

2021-01-13 16:40 UTC, NoahGorny commented
> @NoahGorny sorry. I need more time. I have other priorities at the moment.

I think you misunderstood me :cry: 
I meant that you do not need to feel rushed to do anything here, I totally appreciate the time you contribute to Bash-it, but thats your own time. If you need time for yourself, thats completely fine, I just hope you and your family situation will get better!

2021-01-13 17:06 UTC, cornfeedhobo commented
@NoahGorny No problem at all. I emailed you to explain :)

2021-01-15 19:40 UTC, cornfeedhobo commented on scripts/reloader.bash
> +				while read -r line; do _log_debug "$line"; done <<< "$output"
@NoahGorny I tried re-writing this a few different ways and they are all verbose and less readable. I think this is the most readable format.

2021-01-16 15:31 UTC, cornfeedhobo commented
I'm going to add some tests for this. Hold on to your butts

2021-01-29 01:00 UTC, cornfeedhobo commented
My testing was going smooth until I added a canary to test for a silent failure. I'm going to take a different route. This might take a while. don't wait up.

2021-01-29 02:08 UTC, cornfeedhobo commented
@NoahGorny Well, for now I've pushed the tests I'm working against. You let me know if these cases make sense to you.

2021-01-29 02:58 UTC, cornfeedhobo commented on scripts/reloader.bash
> +				while read -r line; do _log_debug "$line"; done <<< "$output"
this was actually intentional, but it appears that my double subshell method does not allow me to properly catch stdout and send it to the log. instead, everything still prints to the shell.

2021-01-29 11:02 UTC, NoahGorny commented
Hi @cornfeedhobo , nice changes. I think that the test plugins you added should only be present when running the tests, maybe we should store them inside the `test` directory and copy them to the plugin directory on setup?

2021-01-29 14:15 UTC, cornfeedhobo commented
@NoahGorny I think you might have looked at this on your phone or maybe missed that these plugins are in `test/fixtures/`

2021-01-29 14:49 UTC, NoahGorny commented
Whoops, my bad. I will take a look now

2021-01-29 15:16 UTC, NoahGorny commented
Hey @cornfeedhobo, I have made some small changes in order for everything to work, lemme know what you think

2021-01-29 15:32 UTC, cornfeedhobo commented
@NoahGorny Sounds good. Let's leave this PR open for discussion before making any moves. I'm not in a rush and I'm not sure how I feel about the approach. I'm happy to protect users from exits, but I wish it wasn't at the cost of double loading, which I could see becoming expensive for plugins that do things like query brew, which has a very long start time.

2021-01-29 15:35 UTC, cornfeedhobo commented
@NoahGorny oh, if you were trying to make the tests happy, they worked before I pushed and went to bed. Since these don't have pressure to make progress quickly, please don't feel the need to make edits or push it along. I'll get to the tests at my next free time. This is nowhere near the final state I'd like it in anyways. Thanks!

2021-01-29 15:43 UTC, cornfeedhobo commented
@NoahGorny were the tests failing before you made your changes? Is that why you made edits?

2021-01-29 15:49 UTC, NoahGorny commented
> @NoahGorny were the tests failing before you made your changes? Is that why you made edits?

Oh, my bad, I had weird "bash: trap: ./enabled/350---pip.completion.bash: invalid signal specification" lines whenever I reloaded bash-it, so I changed the trap line to use single quotes, this prevented the lines, but fails the test. I should have noticed that....sorry

Do you know why the test fails when using only single quotes in the trap line?

2021-01-29 16:15 UTC, cornfeedhobo commented
The `scripts` variable would have to be a global for the trap to expand at the time of signalling, so I do the expansion up-front.

Looks like you got an error when manually testing?

2021-01-29 16:31 UTC, NoahGorny commented
f

> The `scripts` variable would have to be a global for the trap to expand at the time of signalling, so I do the expansion up-front.
> 
> Looks like you got an error when manually testing?

I got this error every time I reloaded bash-it, in general usage.. I can add a pic if you want

2021-01-29 17:40 UTC, cornfeedhobo commented
@NoahGorny I see it. I'll keep chipping away, but I'm not really in a rush. I'm probably going to pause on this and refocus on the language plugins, which is what I hear about the most with my users.

2021-07-26 05:30 UTC, gaelicWizard commented
$0.02: I'm very much against subshells. They reduce performance, increase resource usage, and cause weird issues like making it difficult to redirect stdout. If we're running scripts from outside this project, then it entirely makes sense that they should be run independently rather than sourced, but if we're importing things from outside that are intended to improve our interactive shell experience (as is the purpose of this project) then we ought to demand that those outside scripts are reliable and predictable. 

I've actually just (barely) started on a PR to try to improve use of bash's own features to reduce calling out to external tools and subshells, but now that I've found this one I may need to rebase here and see how things go.

Alsö, I would heavily object to *any* sourced script *ever* calling `exit`. I'd come out mega-grumpy on their bug tracker.

2021-07-27 13:05 UTC, cornfeedhobo commented
@gaelicWizard I gotta be honest, I haven't touched this in six months, and I'm completely confused by your comment and it's context.

Only your last paragraph made sense to me, and I can only say that I have no control over what a user does. My use case is I have users at a company, and they source a script with `exit` in it. They have zero control over this. I would much rather a loader that never leaves the shell unusable. Most users will not know how to debug once they find themselves with a shell that exits on load.

2021-07-27 18:48 UTC, gaelicWizard commented
> My use case is I have users at a company, and they source a script with `exit` in it. They have zero control over this. I would much rather a loader that never leaves the shell unusable. Most users will not know how to debug once they find themselves with a shell that exits on load.

This makes so much more sense now. 

Alsö, literally just yesterday I found a cursed technique to abuse shell commands, so I may offer a simple (and fun!) PR that might address your use case. 😃

2021-07-27 20:26 UTC, gaelicWizard commented
@cornfeedhobo 
this sounds mad silly...but...try this? It won't work if the `exit` is inside a function...
```
alias exit=return
source /the/bad/script
unalias exit
```
Does that work?

2021-07-27 20:31 UTC, cornfeedhobo commented
It's crazy, but I'm willing to explore the idea. Thanks for sharing!!

Luckily, this isn't a rushed item. I was able to work with each user to identify and fix their problems, but it's what made me consider a generalized loader to handle this.

2021-08-03 20:38 UTC, NoahGorny commented
interesting- I am waiting for a followup from this :smile:

2021-08-03 22:29 UTC, gaelicWizard commented on scripts/reloader.bash
> +_bash-it-load-sources() {
Making this a function ruins all explicit `declare`s, `typeset`s, &c. Bash makes any variables set this way as local to the function, which I suspect is why `reloader.bash` is a script file in the first place.

2021-09-23 01:48 UTC, closed without merging

2021-09-23 20:12 UTC, davidpfarrell commented
Sorry I missed the fun here but wanted to share my ultimate exit vs return hack:

_exit-or-return.sh_
```
#!/usr/bin/env bash

(return 0 2> /dev/null) && return ${1:-0} || exit ${1:-0}
```

_usage_
```
$ /tmp/exit-or-return.sh ; echo $?
0

$ /tmp/exit-or-return.sh 7 ; echo $?
7

$ source /tmp/exit-or-return.sh ; echo $?
0

$ source /tmp/exit-or-return.sh 127 ; echo $?
127
```

Cheers !

2021-09-24 02:54 UTC, gaelicWizard commented
Here's what I use to determine if the script is being sourced or executed:
```
stuff() { :; }

if [[ "${BASH_SOURCE[0]}" != "$0" ]]
then # We are being sourced.
: # do anything necessary for external usage
else # we are being executed 
: # run main function with "$@" and exit
fi
```

I like it because I can have one file with both ends of a client/server setup (e.g., `screen`) functions and whatnot.