linting clean up
Bash-it/bash-it pull request #1762
Opened 2021-01-04 01:53 UTC by cornfeedhobo

## Description

- Lints bash_it.sh
- Ensures all tests are done using double bracket expansions (`[[]]`)

## Motivation and Context

I want to make some changes to the core, but the lack of existing linting is making that difficult.

## How Has This Been Tested?

Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-01-05 01:51 UTC, cornfeedhobo commented
Since this formats `history.bash`, please don't merge until #1764 is resolved.

2021-01-05 07:51 UTC, nwinkler commented
This is great! Looking forward to getting the majority of the codebase in compliance with our guidelines!

2021-01-16 17:35 UTC, NoahGorny requested changes
Left some small comments, otherwise LGTM

2021-01-16 17:35 UTC, NoahGorny commented on bash_it.sh
> +if ! command -v reload &> /dev/null && [[ -n "$BASH_IT_RELOAD_LEGACY" ]]; then
we can use `command_exists` here

2021-01-16 17:35 UTC, NoahGorny commented on lib/history.bash
> +rh() {
I guess this needs a rebase

2021-02-03 19:15 UTC, closed without merging