aliases: Add new git-zsh alias file
Bash-it/bash-it pull request #1831
Opened 2021-02-06 20:30 UTC by NoahGorny

## Description

Adds git-zsh alias file, with aliases copied from [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh).
Currently there is no simple way of updating the aliases easily, and maybe we need to think about it.

## Motivation and Context

Prompted by #1191, this is a re-iteration of #1201.

## How Has This Been Tested?

Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-02-06 20:57 UTC, cornfeedhobo commented
Anyone else torn on whether we should use `zsh-<whatever>` vs `<whatever>-zsh`?

2021-02-06 21:02 UTC, NoahGorny commented
> Anyone else torn on whether we should use `zsh-<whatever>` vs `<whatever>-zsh`?

I went with `git-zsh` as I wanted to keep it close to the `git` alias, it makes more sense this way IMO

2021-02-12 10:08 UTC, NoahGorny commented
Hey @bittner, wanna take a look?

2021-02-13 13:33 UTC, bittner commented
How will we keep this aligned with the Oh My Zsh project implementation?

In [PR #1201](https://github.com/Bash-it/bash-it/pull/1201/files#diff-128cd8e23d4925031bbcc6361903699a6e07dc6ee6b2d486716e41572e49922bR1-R5) I tried to document a scripted approach. Would it make sense to do something similar here?

2021-02-13 14:42 UTC, NoahGorny commented
> How will we keep this aligned with the Oh My Zsh project implementation?
> 
> In [PR #1201](https://github.com/Bash-it/bash-it/pull/1201/files#diff-128cd8e23d4925031bbcc6361903699a6e07dc6ee6b2d486716e41572e49922bR1-R5) I tried to document a scripted approach. Would it make sense to do something similar here?

This is indeed a problem, as the plugin will not work right out of the box..
Simply `sed`ing the file will still not work, as the aliases sometimes use the `$(git_current_branch)` variable.
We might vendor it, and add a file in `init.d` vendor directory which explains how to update, and also defines the needed functions. It will be maintained by us, and when we update, we will change the file if necessary.

The workflow might be `git-vendor` + removing uneeded file + `sed`ing the wanted file + adding `git-zsh` loader that defines the needed functions and load the wanted file

2021-02-13 14:57 UTC, bittner approved these changes

2021-02-13 14:57 UTC, bittner approved these changes

2021-02-13 14:58 UTC, bittner commented
How may approvals does a PR need? :zany_face:

2021-02-24 17:08 UTC, NoahGorny commented
> How may approvals does a PR need? 🤪

haha, I still need to add some kind of script that updates this completion.. so its not ready yet.
thanks for the CR though @bittner

2021-08-03 20:48 UTC, NoahGorny commented
I am also okay with vendoring it as it is right now- and update it once in a while. what do you think @cornfeedhobo @bittner ?

2021-08-13 01:51 UTC, gaelicWizard commented
May I suggest that the new alias file be named `git-omz`? It's providing aliases from _Oh My Zsh_, not from _Zsh_ itself. Just a nitpick... 😆

2021-08-14 08:03 UTC, NoahGorny commented
> May I suggest that the new alias file be named `git-omz`? It's providing aliases from _Oh My Zsh_, not from _Zsh_ itself. Just a nitpick...

Nice idea- done!

2021-09-17 12:02 UTC, NoahGorny commented
Howdy folks!
I have added `ohmyzsh` as a vendored library using `git-vendor` with @buhl changes. this will hopefully be easier to maintain, although I still changed some code from the plugin so it will be loaded successfully
let me know what you think @cornfeedhobo @bittner @gaelicWizard

2021-09-19 17:08 UTC, cornfeedhobo commented
@NoahGorny I like it. The only question I have remaining is if you are open to the idea of applying patches to vendored libs and what that should look like. I still need to submit a patch to deal with pre-exec's clobbering of `ignoreboth` and `ignorespace`, and in this case I'd rather not pollute the global namespace with the vaguely named `is-at-least` function.

2021-09-19 19:49 UTC, gaelicWizard commented
> The only question I have remaining is if you are open to the idea of applying patches to vendored libs and what that should look like. I still need to submit a patch to deal with pre-exec's clobbering of `ignoreboth` and `ignorespace`, and in the case of this PR, I'd rather not pollute the global namespace with the vaguely named `is-at-least` function.

I've already submitted a PR upstream for _preexec_'s history shenanigans, based on an existing PR that they had been ignoring. They did accept an unrelated PR for unbound parameters, but no traction on this one yet.

As for weird function names, we can handle that in our loader. I'll give it a go and post it here later tonight. I'd like to suggest that it's quite valuable to avoid, whenever possible, carrying any patches over vendor'd libs.

2021-09-19 19:59 UTC, cornfeedhobo commented
@gaelicWizard I think you saw my open issue with preexec. They aren't going to budge on this one. We either maintain a fork in our github namespace, and patch that way, or figure out a scheme for patching on PR and documenting the diff.

2021-09-19 20:13 UTC, gaelicWizard commented
@cornfeedhobo, I did a whole PR which keeps their desired behavior in place, but behaves properly when we change it. My idea was to let them have their way, and then we just set `$HISTCONTROL` back after we load them.

2021-09-20 11:54 UTC, NoahGorny commented
> @NoahGorny I like it. The only question I have remaining is if you are open to the idea of applying patches to vendored libs and what that should look like. I still need to submit a patch to deal with pre-exec's clobbering of `ignoreboth` and `ignorespace`, and in the case of this PR, I'd rather not pollute the global namespace with the vaguely named `is-at-least` function.

The problem with patches is that we need to apply them somewhere, probably during installation. We need to think about how we do this and how other places are doing it. Simply having patches around isn't going to cut it sadly. I also think that committing directly into the vendored file like I did isn't great, but it is the simplest solution currently

2021-09-21 18:06 UTC, cornfeedhobo commented
> The problem with patches is that we need to apply them somewhere, probably during installation. We need to think about how we do this and how other places are doing it. Simply having patches around isn't going to cut it sadly. I also think that committing directly into the vendored file like I did isn't great, but it is the simplest solution currently

@NoahGorny Agreed. Maybe a viable solution is to fork their project, patch, and use [the pull bot](https://github.com/wei/pull) to automate the watching of upstream updates.

2022-01-04 05:28 UTC, gaelicWizard requested changes

2022-01-04 05:28 UTC, gaelicWizard commented on aliases/available/git.aliases.bash
> +_bash_it_git_aliases_enabled=true
Can you use `_bash-it-component-item-is-enabled()`?

2022-01-04 05:28 UTC, gaelicWizard commented on test/lib/search.bats
> +    echo $alias
Doesn't the echo defeat the test?

2022-01-04 05:28 UTC, gaelicWizard commented on aliases/available/git-omz.aliases.bash
> +cite 'about-alias'
Shouldn't need this `cite`

2022-01-04 05:28 UTC, gaelicWizard commented on aliases/available/git-omz.aliases.bash
> +	_log_error "git-omz aliases are incompatible with regular git aliases"
Can you use `_bash-it-component-item-is-enabled()`?

2022-01-18 23:16 UTC, gaelicWizard commented on aliases/available/git-omz.aliases.bash
> +fi
```suggestion
if _bash-it-component-item-is-enabled aliases git; then
	_log_warning "git-omz aliases are incompatible with regular git aliases"
	return 1
fi
```

2022-01-18 23:17 UTC, gaelicWizard requested changes
I added suggested use of `_bash-it-component-item-is-enabled aliases git`. I think GitHub just lets you click accept if you like it and it commits it directly to the PR

2023-05-27 13:42 UTC, samtsevich commented
Hello all,
Is there any news about merging these changes into `master`?

2024-03-10 00:30 UTC, samtsevich commented
Hello again :)
I asked this question a year ago and still would like to see this implementation merged into `master`.
Is there any chance of seeing this in the near future?

2024-11-07 11:20 UTC, seefood approved these changes
I think this is close to perfect.
@NoahGorny shall I merge it as is or do you want to give it the last round of improvements per the remarks posted?

2025-04-30 11:08 UTC, seefood approved these changes

2025-04-30 11:08 UTC, merged