completion: pip: Only invoke pip when trying to complete it
Bash-it/bash-it pull request #1834
Opened 2021-02-06 21:32 UTC by NoahGorny

## Description

Invokes pip only when actively trying to complete it.

## Motivation and Context

This should greatly reduce shell load time, as the pip invocation takes
a lot of time.

## How Has This Been Tested?

Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-02-24 17:09 UTC, NoahGorny commented
@cornfeedhobo @davidpfarrell @nwinkler what is your opinion on this? 
it greatly improves shell load time for me

2021-03-01 12:45 UTC, cornfeedhobo commented
@NoahGorny I'd love to test this more thoroughly soon, but I'm a little bogged down. If you're okay waiting through this week, I'll probably get to it.

2021-07-14 16:41 UTC, cornfeedhobo approved these changes
Beautiful. Let's definitely get this out.

2021-07-14 18:18 UTC, cornfeedhobo requested changes
Looks great and tests great, but small change requested. Thanks!

2021-07-14 18:18 UTC, cornfeedhobo commented on completion/available/pip.completion.bash
> +	function _pip_lazy() {
Most popular tools follow the pattern `__<tool with underscores>_complete_<function name>` and I think we should to.

```suggestion
	function __bash_it_complete_pip() {
```

2021-07-14 18:35 UTC, cornfeedhobo commented
I'm also thinking we might want to generalize the lazy loading of any function, but I think I could handle that in a follow up PR.

2021-08-03 19:42 UTC, NoahGorny commented
@cornfeedhobo finally got around to actaully doing it, thanks for the CR :smile:

2021-08-03 23:41 UTC, hongyi-zhao commented
> @cornfeedhobo finally got around to actaully doing it, thanks for the CR smile

What's the meaning of `CR` used by you here?

2021-08-04 01:26 UTC, davidpfarrell approved these changes
First I was worried about the surprised delay the user might get on first use, *but* TIL that [bash-completion](https://github.com/scop/bash-completion) loads completions lazily by default.

We might consider a framework to also lazy-load completions by default, but until then, this seems legit.

2021-09-19 05:01 UTC, NoahGorny commented
@cornfeedhobo ping :smile:

2021-09-19 16:19 UTC, cornfeedhobo approved these changes
This looks great. There is a small lag on the first tab, but that's to be expected with lazy loading.

2021-09-20 11:47 UTC, merged