completion (feature): dart cli
Bash-it/bash-it pull request #1852
Opened 2021-03-15 14:49 UTC by tbhaxor

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

2021-03-15 21:17 UTC, NoahGorny requested changes
hey @tbhaxor, I added some comments, you are welcome to take a look

nice job :smile:

2021-03-15 21:17 UTC, NoahGorny commented on completion/available/dart.completion.bash
> +	local DEFAULT="$BASE --authtoken --region"
you did not define `$BASE`, also `DEFAULT` is unused

2021-03-15 21:17 UTC, NoahGorny commented on completion/available/dart.completion.bash
> +		*)
please do like I did, and complete all the options only for the command itself (`dart`), in the default case, dont complete anything

2021-03-16 21:55 UTC, tbhaxor commented
@NoahGorny I will fix this in this weekend

2021-03-25 20:24 UTC, tbhaxor reviewed
@NoahGorny This is done

2021-03-26 19:27 UTC, tbhaxor commented
@NoahGorny Its done plz chk

2021-03-28 20:29 UTC, NoahGorny approved these changes
Lgtm

2021-03-29 12:30 UTC, tbhaxor commented
> I want to add nested completion for `pub` command
> 
> ```
> $ dart pub <TAB> <TAB>
> cache deps downgrade get global logout outdated publish run upgrade uploader version
> ```
> 
> How can I achieve this?
> 
> Thanks in advance

@NoahGorny ping

2021-03-29 19:43 UTC, NoahGorny commented
> > I want to add nested completion for `pub` command
> > ```
> > $ dart pub <TAB> <TAB>
> > cache deps downgrade get global logout outdated publish run upgrade uploader version
> > ```
> > 
> > 
> > How can I achieve this?
> > Thanks in advance
> 
> @NoahGorny ping

I dont understand what you mean, this is my output:
```
$ dart pub <TAB> <TAB>
cache        downgrade    global       --help       --no-trace   publish      --trace      uploader     --verbose    --version
deps         get          -h           logout       outdated     run          upgrade      -v           --verbosity  version
```

This is not what you want?

2021-04-01 22:20 UTC, tbhaxor commented
@NoahGorny My bad, I wasn't clear enough

See, we have completed for dart, and its arguments like `dart pub`. But how to add the completion for `dart pub add`


![image](https://user-images.githubusercontent.com/28386721/113360002-8dce8000-9366-11eb-8b53-f11f9d2314a0.png)

I need to add the completions for `dart pub add` somehow in `pub` case

2021-04-01 22:22 UTC, tbhaxor commented
@NoahGorny Also for such KB, it's hard to search through pull requests. Should we start GitHub discussions for such things?

2021-04-11 18:35 UTC, tbhaxor commented
@NoahGorny Ping 😄

2021-04-14 12:39 UTC, NoahGorny commented
> @NoahGorny My bad, I wasn't clear enough
> 
> See, we have completed for dart, and its arguments like `dart pub`. But how to add the completion for `dart pub add`
> 
> ![image](https://user-images.githubusercontent.com/28386721/113360002-8dce8000-9366-11eb-8b53-f11f9d2314a0.png)
> 
> I need to add the completions for `dart pub add` somehow in `pub` case

You can use the `COMP_WORDS` variable for that, see what we do in `bash-it.completion.bash`, there are nice examples there

2021-08-03 20:39 UTC, NoahGorny commented
I will merge this as is- after I will release a stable version today

2021-08-03 20:58 UTC, merged