Delete `.shellcheckrc`
Bash-it/bash-it pull request #1947
Opened 2021-09-14 20:23 UTC by gaelicWizard

## Description
Turns out that there is a file in the repo root which disabled checks for unbound variables.

## Motivation and Context
I've done a *lot* of work finding and fixing these problems...which would have been detected by shellcheck if it hadn't been disabled.

## How Has This Been Tested?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-09-14 20:54 UTC, gaelicWizard commented
@NoahGorny, can you take a look at this one? I'd like to get this merged before I do anything else.

2021-09-15 14:15 UTC, NoahGorny commented
Hi @gaelicWizard- great work!
This seems like a huge diff, but really isn't. I will try to look at this in the upcoming days in order to merge it

2021-09-16 18:30 UTC, NoahGorny requested changes
I had only a comment, otherwise lgtm

2021-09-16 18:30 UTC, NoahGorny commented on .github/workflows/ci.yml
> -        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, macos-11.0]
This does not seem related to this PR, if you want to discuss this, you should open another PR!

2021-09-16 19:05 UTC, gaelicWizard commented on .github/workflows/ci.yml
> -        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, macos-11.0]
Sorry, the test was failing as this runner wouldn't start. It's got ń̥o҉̙̻̖̲̮͓̩̀t̵̬̳͔ḩ̡̪͇͈i̼̦̮̙͝n̸̸̲̲͍̟g͏̭͖̠̩̭ else to do with it!

Although, now it seems like maybe the 16.04 broke a week early and may be working again. I'll try it without and we'll see if it goes!

2021-09-16 19:09 UTC, gaelicWizard commented on .github/workflows/ci.yml
> -        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, macos-11.0]
Their announcement: https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

2021-09-16 19:48 UTC, NoahGorny approved these changes

2021-09-16 19:49 UTC, NoahGorny commented on .github/workflows/ci.yml
> -        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, macos-11.0]
Alrighty, if the ubuntu 16 jobs are indeed going down, we can remove them in here as well

2021-09-18 09:50 UTC, merged