DRAFT: Fix SC2154 from themes
Bash-it/bash-it pull request #1954
Opened 2021-09-19 04:06 UTC by gaelicWizard

## Description
As a follow on to my work removing `.shellcheckrc` from hiding problems, this PR addresses these problems inside individual themes.

## Motivation and Context
Due to the nature of themes, they use a huge number of variables from the themes lib and colors lib, but `shellcheck` is unable to follow the code flow so can't tell if these variables are defined or not. This patchset is meant to improve code so that `shellcheck` can either see the variables properly, or can trust that we have it under control. 

## How Has This Been Tested?
`set -u`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2021-09-19 07:00 UTC, gaelicWizard commented
This is ready to review and hopefully ready to merge 😃

2021-09-22 21:15 UTC, gaelicWizard commented
After going through all these themes, I have this suspicion that a lot of the themes are broken.

2021-09-25 15:43 UTC, gaelicWizard commented
@davidpfarrell, @cornfeedhobo, @NoahGorny, I'd love to get some feedback on this one when any of you have time!

I've used `?` for everything that seems pretty rock-solid definitely already defined (e.g. colors), and `:-` for everything that looks like a user-configurable preference (so everything still works no matter whether it exists or not). I've alsö run `shfmt` using current project settings and added to `clean_files.txt`. There shouldn't be any behavior changes at all (except perhaps if there were an unexpectedly failing conditional due to missing parameter).

A couple of things I've noticed: 
- some of the logic in some themes is copy/pasta from another, with slight divergence
- some of the logic does not make sense to me; I don't understand what it's supposed to do. 
- in a few places, variables are references which exist nowhere else in the codebase...
- something like half of the special characters in the themes show as the Unicode box on my system; is this normal? Is there a reference which shows them correctly (screenshots)?

2021-09-25 16:07 UTC, davidpfarrell requested changes
I find this PR to be too large and risky - Although not optimal, I might like to see per-theme PR's here.

Or maybe make a few bigger PRs with *easy to review* changes and leave the more complex changes for single-theme PRs ...

2021-09-25 16:07 UTC, davidpfarrell commented on themes/barbuk/barbuk.theme.bash
> +: "${BARBUK_GIT_DEFAULT_CHAR:='  '}"
```
< SCM_GIT_CHAR_DEFAULT=${BARBUK_GIT_DEFAULT_CHAR:='  '}
> : "${BARBUK_GIT_DEFAULT_CHAR:='  '}"
```

With these changes, `BARBUK_GIT_DEFAULT_CHAR` still gets its defaulting assignment, but where in the code does `SCM_GIT_CHAR_DEFAULT` come to have the value of `BARBUK_GIT_DEFAULT_CHAR` ?

2021-09-25 16:07 UTC, davidpfarrell commented on plugins/available/alias-completion.plugin.bash
> -		# shellcheck disable=SC2154 # see `eval` above
Not a theme file

2022-01-12 22:20 UTC, gaelicWizard commented
@davidpfarrell, @NoahGorny, this PR is now *much* smaller since the intermediate PRs have been merged.

2022-02-15 21:13 UTC, NoahGorny commented
Hi @gaelicWizard, I think we should probably split this up for even more parts, this will make it much easier to review for me (the changes are unrelated to each other)

2022-02-15 21:17 UTC, gaelicWizard commented
@NoahGorny, most of these already have open PRs. The "base" theme has #2038, pure has #2068, &c. I expect this PR to shrink even more as those are merged and leave only a few tidbits after.

2022-03-04 22:57 UTC, gaelicWizard commented
This bad boy has shrunk down pretty small. Three files left: bargbuk, binaryanomaly, and modern. I think that's fair to review together.

2024-11-07 12:19 UTC, seefood commented
I'll gladly review it if you could please merge the latest master, there are some conflicts in barbuk.

2025-03-24 14:15 UTC, seefood approved these changes
needs to be tested after merge.

2025-04-26 14:51 UTC, seefood approved these changes

2025-04-26 14:52 UTC, merged