Added alias ls='ls -F'
Bash-it/bash-it pull request #1991
Opened 2021-12-02 18:22 UTC by noviicee

## Description

Added the option -F in alias ls.

## Motivation and Context

closes #1206 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

2021-12-02 18:29 UTC, noviicee commented
Kindly let me know if any changes are required. I'll be happy to do so. This is my first PR :)

2021-12-02 21:31 UTC, davidpfarrell requested changes
Sending back for changes ...

2021-12-02 21:31 UTC, davidpfarrell commented on aliases/available/general.aliases.bash
> +alias ls='ls -F'
This overwrites the `ls` alias settings above (see lines 4-10)

2021-12-02 21:31 UTC, davidpfarrell commented on aliases/available/msys2.aliases.bash
> +alias ls="ls -F"
This overwrites the `ls` alias settings above (see line 12).

If used, the `-F` should be made part of `LS_COMMON`

2021-12-11 18:26 UTC, noviicee commented
Okay. Will fix it by tomorrow 👍

2021-12-27 20:11 UTC, gaelicWizard commented
I like `-F` and support including it here

2022-01-03 11:44 UTC, NoahGorny commented
gentle ping @noviicee

2022-01-03 18:12 UTC, noviicee commented
So sorry for the delay. Changing the alias name immediately.

2022-01-04 19:27 UTC, davidpfarrell approved these changes
Approved, thanks !

2022-01-07 07:10 UTC, merged