Theme/powerline.base
Bash-it/bash-it pull request #2050
Opened 2022-01-17 21:09 UTC by gaelicWizard

## Description
Change `theme/gitline/powerline.base` and `theme/powerline/powerline.base` to match more closely. Alsö, lint `theme/gitline`.

## Motivation and Context
Of all the powerline-based themes, `theme/gitline` had a whole copy of `powerline.base.bash`. By updating them to match more closely, we may be able to eliminate the duplicate file in the future. 

## How Has This Been Tested?
Since I haven't used the powerline* themes much, this is hard for me to test as I'm not used to what "normal" looks like. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2022-01-26 15:37 UTC, NoahGorny commented
why wouldnt we remove the duplication here altogether? how different is `gitline` from the regular `powerline`?

2022-01-26 15:44 UTC, gaelicWizard commented
It adds hardcoded foreground colors to nearly every prompt segment. By harmonizing the files, I can see the ~15 or so differences that are different very easily. But, I don't have enough experience with the power line themes to be confident about making substantive changes. The goal is definitely to remove the duplicate file, but only after making sure we're not losing capability or breaking anything. 

Besides, this alsö adds several possible segments to gitline that were previously not available.

2024-11-05 15:55 UTC, seefood requested changes
Seems legit in general, can you please merge it with master so we can make sure it passes the tests smoothly?

2024-11-07 09:31 UTC, seefood approved these changes

2025-01-12 08:44 UTC, merged