bug: Use C style strings when checking for invalid alias characters
Bash-it/bash-it pull request #2188
Opened 2023-01-11 21:43 UTC by convergedtarkus

## Description
Before, the '\n' in the characters being checked would be interpreted as 'n' rather than newline meaning that any alias who's command contained the letter 'n' would be incorrectly skipped.

## Motivation and Context
This bug is annoying as certain aliases will appear to randomly not have completion for them.

## How Has This Been Tested?
- Tests pass locally.
- My `alias gb='git branch'` alias now shows the correct completion
- Tested that the C style string usage still correctly identifies aliases with disallowed characters

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

2023-01-11 21:49 UTC, convergedtarkus commented
Closing while I verify more details. Sorry for opening early.

2023-01-18 19:01 UTC, convergedtarkus commented
Those CI and lint failures do not look related to my change. Anyone have ideas what's up with that?

2023-01-21 18:22 UTC, davidpfarrell requested changes
Thanks for submitting this PR !  See my notes regarding simplifying the string for clarity.

2023-01-21 18:22 UTC, davidpfarrell commented on completion/available/aliases.completion.bash
> +		chars=$'\|\&\;\)\(\n\<\>'
Although this does fix the bug (good find!), it turns out the `\` aren't needed in this context at all, and this essentially just adds the `\` character to the match list (6 times!) ... Assuming we don't care to _actually_ match `\`, this is sufficient:

```
chars=$'|&;()<>\n'
```
And *much* easier to read.
I'm going to recommend we update this PR to the more simple string.

2023-01-23 17:21 UTC, convergedtarkus commented
@davidpfarrell Thank you for that. I added the \ for the newline locally while testing but totally forget to commit it.

2023-01-25 15:36 UTC, convergedtarkus commented
What needs to happen at this point to get this merged?

2023-01-25 23:56 UTC, davidpfarrell commented
The failing lint test *seems* unreleated but it does look like your fork's branch and master both diverged beyond this PR, which may be contributing.

The merge looks clean, so I'm going to go ahead and merge it.

2023-01-25 23:56 UTC, merged