Implement yarn completion
Bash-it/bash-it pull request #2190
Opened 2023-02-01 10:29 UTC by tbhaxor

## Description

This PR will implement yarn completion from the external vendor

## Motivation and Context

Yarn is required while developing the nodejs projects and often as project grows completion is required. This PR fixes that problem.

## How Has This Been Tested?
Locally by sourcing

## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/28386721/216018327-b95f72dd-6cb4-480b-bff5-e86e821ddf44.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

2023-02-09 11:18 UTC, tbhaxor commented
@NoahGorny @davidpfarrell could you review it and merge. I need it urgently

2023-02-09 16:35 UTC, davidpfarrell requested changes
Hey !  So the .bash file doesn't match the pattern used in other vendor competions:
_django.completion.bash_
```
# shellcheck shell=bash
about-completion "django completion"
# shellcheck disable=SC1090
source "${BASH_IT}"/vendor/github.com/django/django/extras/django_bash_completion
```
_apm.completion.bash_
```
# shellcheck shell=bash
about-completion "apm completion"
# shellcheck disable=SC1090
source "${BASH_IT}"/vendor/github.com/vigo/apm-bash-completion/apm
```
_jboss5.completion.bash_
```
# shellcheck shell=bash
about-completion "jboss5 completion"
# shellcheck disable=SC1090
source "${BASH_IT}"/vendor/github.com/rparree/jboss-bash-completion/jboss5
```
_jboss7.completion.bash_
```
# shellcheck shell=bash
about-completion "jboss7 completion"
# shellcheck disable=SC1090
source "${BASH_IT}"/vendor/github.com/rparree/jboss-bash-completion/jboss7
```

Mind taking a quick pass to normalize yours?
Also wondering why 2207 vs 1090 in your case?

-D

2023-02-10 13:12 UTC, tbhaxor commented
@davidpfarrell Any reason why arent we using git submodules?

2023-02-10 13:19 UTC, tbhaxor commented
> Also wondering why 2207 vs 1090 in your case?

Fixed lint errors

2023-02-10 19:55 UTC, davidpfarrell requested changes
I'm surprised the lint check didn't hit the SC1090 - Although I realize now that the other completions are dealing with it wrong ie. we should use `source=` instead of disabling it.

So check the repository for the completion, I notice two things:
* This is already available in homebrew bash-completions
* This only officially supports ^4.x

Not sure if any doc changes or checks should be added but wanted to call it out ...

Changes I do recommend:
* Add repo url to about - Not sure if there's a built-in meta tag for it?
* Add the SC1090 line from the example - Not sure why its not hitting but I'm sure it will in the future and don't want to break future builds because of it.

2023-02-14 19:03 UTC, davidpfarrell commented
> @davidpfarrell @NoahGorny can we merge this if everything is fine. My team is waiting for this

Sorry @tbhaxor  my previous comment _was_ a request-for-changes comment, re:

> Changes I do recommend:
>
>Add repo url to about - Not sure if there's a built-in meta tag for it?
Add the SC1090 line from the examples - Not sure why its not hitting but I'm sure it will in the future and don't want to break future builds because of it.

2023-02-15 01:42 UTC, tbhaxor commented
@davidpfarrell SC1090 is not triggering on my end either, but 1091 is triggering. Do you want me to disable it also?

![Screenshot_20230215_071152](https://user-images.githubusercontent.com/28386721/218905750-18371f07-d5b7-49f5-92f2-68878675d4fa.png)

2023-02-15 06:15 UTC, davidpfarrell commented
@tbhaxor Does 1091 trigger even when disable=SC1090 is present?

The two codes are related and in this case 1091 is being triggered by new-ish behavior for 1090 errors.

But it's unclear from the docs if disabling 1090 also disables 1091 in this special case.

My thought is is _might_ so try just disabling 1090 and see if that clears ...

Alternatively you could add `source=../../vendor/github.com/dsifford/yarn-completion/yarn` and make shellcheck happy :)

* https://www.shellcheck.net/wiki/SC1090
* https://www.shellcheck.net/wiki/SC1091

2023-02-22 13:42 UTC, tbhaxor commented
Again, where did you get it triggered or just assuming it could trigger?

2023-02-22 16:16 UTC, davidpfarrell approved these changes

2023-02-22 16:20 UTC, davidpfarrell commented
Failing lint errors presumed fixed in #2192 which has been merged ...

2023-02-22 16:20 UTC, merged