Add new feature to base.plugin.bash
Bash-it/bash-it pull request #2257
Opened 2024-07-03 18:04 UTC by TheMadTomato

## Description

New function labeled `rex()`  servers a single purpose. Replace the file extensions of multiple file at once. File extensions usually does not quite matter in bash, but there is a few cases when one might needs to and this function simplifies the process from multiple commands into one.

## The Function
```sh
function rex() {
	about 'mass replace of the extension of multiple files'
 	param '1: extension to replace'
  	param '2: new extenstion'
   	example 'rex txt md'
    	group 'base'
	local ext2replace="${1:-}"
 	local newext="${2:-}"
  	local files=(`ls *.$ext2replace`)
   	for file in "${files[@]}"; do mv "$file" "${file/%.$ext2replace/.$newext}"; done
}
```

## How Has This Been Tested?

Created multiple test files with different extensions, than proceeded to use `rex` to only change the specified extension which worked flawlessly

**Testing Environment**
- OS : Debian GNU/Linux 12 (bookworm) x86_64
- VER: 6.1.0-21-amd64 
- Bash Ver: 5.2.12
- Computer: Lenovo Thinkpad P52s

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

2024-11-05 16:31 UTC, seefood requested changes

2024-11-05 16:31 UTC, seefood commented on aliases/available/general.aliases.bash
> +alias d='cd /home/$USER/Downloads' # Go to the Downloads directory
This is a bit too short and already taken by a function for the fasd plugin. please rename to something that won't clobber or move to your private alias file.

2024-11-05 16:31 UTC, seefood commented on plugins/available/base.plugin.bash
> +function rex() {
There is already a package in Ubuntu and other distros called rex and I would rather not have them clash. Could you consider naming it renex or rext?

2024-11-05 16:31 UTC, seefood commented on plugins/available/base.plugin.bash
> + 	param '1: extension to replace'
The indentation is mixed spaces and tabs, please align all to just tabs. Thanks!

2025-02-27 14:17 UTC, akinomyoga commented on plugins/available/base.plugin.bash
> +  	local files=(`ls *.$ext2replace`)
```suggestion
  	local files=(*."$ext2replace")
```

`` `ls *.$foo` `` is subject to unwanted word splitting and pathname expansions. One should simply use `*."$foo"`. In this case, one should check the generated filenames exist because the literal `'*.txt'` remains if the matching filename does not exist and `shopt -s nullglob` is not set.

2025-02-27 14:33 UTC, akinomyoga commented on plugins/available/base.plugin.bash
> +   	for file in "${files[@]}"; do mv "$file" "${file/%.$ext2replace/.$newext}"; done
- `$ext2replace` should be quoted. Otherwise, `$ext2replace` is treated as a glob pattern.
- In Bash >= 5.1, when `pathsub_replacement` is turned on (which is the default), `&` inside `$newext` would be expanded to the original matching. It is unusual to include `&` in the filename extension, but it would still cause unexpected results when the user specifies such an extension.
  - One *naive* workaround would be to quote `$newext` as `"$newext"`, but it causes another issue with Bash <= 4.2 or when `shopt -s compat42` is turned on: For example, `a=x.dat; echo "${x/".dat"/".txt"}"` would result in `a".txt"`.
  - To properly handle this, one needs to save, unset, and restore the shell setting `patsub_replacement`.
  - Or another way to work it around is to assign the replacement result to a shell variable with no quoteing of the entire RHS: `local dst=${file/%."$ext2replace"/."$newext"}`. This works under an arbitrary combination of `shopt -q patsub_replacement` and `shopt -q compat42`.

2025-02-27 15:08 UTC, seefood commented
@TheMadTomato hey paul, would you like to try merging with the master and fix the suggested problems please?

2025-02-27 15:42 UTC, TheMadTomato commented
Hello, Sorry i missed  your comments.
I will tend to all the points you have given me very soon.

2025-03-22 14:06 UTC, seefood commented on plugins/available/base.plugin.bash
> +function rex() {
```suggestion
function renex() {
```

2025-03-22 14:07 UTC, seefood commented on plugins/available/base.plugin.bash
> + 	param '1: extension to replace'
```suggestion
	param '1: extension to replace'
```

2025-03-22 14:21 UTC, akinomyoga commented on plugins/available/base.plugin.bash
> +   	for file in "${files[@]}"; do mv "$file" "${file/%.$ext2replace/.$newext}"; done
```suggestion
	for file in "${files[@]}"; do
		local dst=${file/%."$ext2replace"/."$newext"}
		mv "$file" "$dst"
	done
```

2025-03-22 14:24 UTC, akinomyoga commented on plugins/available/base.plugin.bash
> + 	param '1: extension to replace'
The same adjustments are needed also for the other added lines.

2025-03-22 14:59 UTC, seefood commented on aliases/available/general.aliases.bash
> +alias d='cd /home/$USER/Downloads' # Go to the Downloads directory
```suggestion
alias dow='cd /home/$USER/Downloads' # Go to the Downloads directory
```

2025-03-22 15:03 UTC, seefood commented on plugins/available/base.plugin.bash
> + 	local newext="${2:-}"
```suggestion
	about 'mass replace of the extension of multiple files'
	param '1: extension to replace'
	param '2: new extenstion'
	example 'rex txt md'
	group 'base'
	local ext2replace="${1:-}"
	local newext="${2:-}"
```

2025-03-22 15:05 UTC, seefood commented on aliases/available/general.aliases.bash
> +alias rmrf='rm -rf'
```suggestion
alias rmrf='rm -rf'
```

2025-03-23 16:25 UTC, merged